### PR TITLE
Remove Kube Config Script for AWS EKS

### PR DESCRIPTION
**Pull request by angudadev**
Hi @evberrypi 

as setup-kube-config.sh not working properly removing now. 

Thanks,
Anurag G

### CODE REVIEW

**Comment by evberrypi** [comment]
Can you re-generate the documentation in the readme? `terraform-docs markdown .` ?

**Comment by MaggieXJZhang** [comment]
Does this affect any steps in bring up the cluster? I only see removals of lines, but no edits to documentation.

**Comment by angudadev** [comment]
@evberrypi done with `terraform-docs markdown .`

@MaggieXJZhang it's affecting ti bring up and destroying the cluster so removing that feature and updated the docs

**Review by evberrypi — APPROVED** [review]
LGTM! Thanks @angudadevops

**Pull request merged**
